### PR TITLE
Remove the TrieKey trait in favour of Eq + Hash bounds

### PR DESCRIPTION
**Pull request by andrewhickman**
See issue https://github.com/michaelsproul/rust_sequence_trie/issues/34

### CODE REVIEW

**Comment by michaelsproul** [comment]
This looks good, however I wouldn't mind keeping the `TrieKey` trait (and changing it to be equivalent to `Eq + Hash`), so that it's possible to swap out the backing `HashMap` for another type of map. At some point I'm planning to add `BTreeMap`s as backing storage (because they sort keys), using `#[cfg(feature = "btreemap_backing")]`. The definition of `TrieKey` might then look like this:

```rust
#[cfg(not(feature = "btreemap_backing"))]
pub trait TrieKey: Eq + Hash {}

#[cfg(feature = "btreemap_backing")]
pub trait TrieKey: Ord {}
```

**Comment by andrewhickman** [comment]
For now I've just changed the definition of TrieKey and changed all the Hash + Eq bounds back.

**Comment by michaelsproul** [comment]
Ah, I forgot to change the title before I merged. Oh well. Hopefully the commit message isn't too confusing to anyone else who's reading.

**Comment by michaelsproul** [comment]
I released 0.3.4 on crates.io: https://crates.io/crates/sequence_trie/0.3.4

**Pull request merged**
