### PR TITLE
Extend lookup methods with Borrow

### PR DESCRIPTION
**Pull request by sfackler**

### CODE REVIEW

**Comment by sfackler** [comment]
Oops, gotta fix something, 1 sec.

**Comment by sfackler** [comment]
Add on a commit to fix some things I missed in #32 :)

**Comment by michaelsproul** [comment]
I'll release version 0.3.2 to crates.io with this change unless you have any more changes coming...

I realised I probably should have made yesterday's release 0.4.0, but that ship has sailed, so it seems best to call the next release 0.3.2.

**Comment by sfackler** [comment]
Nope, that's it for now I think. Thanks!

**Comment by michaelsproul** [comment]
Ok! Published 0.3.3 because I accidentally released code with an unused import as 0.3.2, d'oh! Not having a good time with these releases 😬

**Pull request merged**
